#lang racket

(require "../music.rkt")
(require "../eval.rkt")
(require "../perform.rkt")

(define my-comp
  (in ([start 0] [end 32] [voices '(S A T B)])
    (define (theme1 o)
      (-- ()
        (4 (note 'a 0 o))
        (4 (note 'b 0 o))
        (4 (note 'c 0 (+ o 1)))
        (4 (note 'd 0 (+ o 1)))))
    (define (theme2 o)
      (-- ()
        (3  (note 'e 0 o))
        (.5 (note 'd 0 o))
        (.5 (note 'c 0 o))
        (3  (note 'd 0 o))
        (.5 (note 'f 1 o))
        (.5 (note 'g 1 o))
        (4  (note 'a 0 o))
        (4  (note 'g 1 o))))
    (in ([voices '(A)]) (theme1 4))
    (in ([start 8] [voices '(T)]) (theme1 3))
    (in ([voices '(S)]) (theme2 5))
    (-- ([start 8] [voices '(B)])
      ;; should be able to leave this first length off...
      (12 (theme2 2)) (4 (note 'e 0 2)) (8 (note 'a 0 2)))
    (in ([start 24] [end 32] [voices '(S)]) (note 'a 0 5))
    (in ([start 24] [end 32] [voices '(A)]) (note 'c 1 4))
    (in ([start 24] [end 32] [voices '(T)]) (note 'e 0 3))))

(play (perform my-comp 240))
